version: "3"
services:
    mysql:
        image: mysql:latest
        container_name: myproject-mysql
        command: 
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--default-authentication-plugin=mysql_native_password'
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=myuserpass
        volumes:
            - "./db:/var/lib/mysql" 